[package]
name = "team-snowdust/feature-flags"
version = "0.1.0"
description = "A feature flags library"
license = "MIT"
authors = ["Lucas Gangstad <lucas@lasttalon.dev>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "*.spec.lua",
    "*.dev.lua",
    "tests",
    "docs",
    "aftman.toml",
    "moonwave.toml",
    "selene.toml",
    "stylua.toml",
    "testez-companion.toml",
    "sourcemap.json",
    "test.project.json",
    "testez.yaml",
]

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "lasttalon/signal@0.1.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
